/*CRIEI O ESQUEMA PARA REALIZAR ALGUNS TESTES*/
CREATE TABLE DEPTO (
    CODDEPTO  NUMBER NOT NULL,
    NOMEDEPTO VARCHAR2(100)
);

ALTER TABLE DEPTO ADD CONSTRAINT DEPTO_PK PRIMARY KEY ( CODDEPTO );

CREATE TABLE DISCIPLINA (
    CODDEPTO    NUMBER NOT NULL,
    NUMDISC     NUMBER NOT NULL,
    NOMEDISC    VARCHAR2(100),
    CREDITODISC NUMBER
);

ALTER TABLE DISCIPLINA ADD CONSTRAINT DISCIPLINA_PK PRIMARY KEY ( NUMDISC,
                                                                  CODDEPTO );

CREATE TABLE HORARIO (
    CODDEPTO   NUMBER NOT NULL,
    NUMDISC    NUMBER NOT NULL,
    ANOSEM     VARCHAR2(5) NOT NULL,
    SIGLATUR   VARCHAR2(20) NOT NULL,
    DIASEM     VARCHAR2(10) NOT NULL,
    HORAINICIO VARCHAR2(10) NOT NULL,
    CODPREDIO  NUMBER NOT NULL,
    NUMSALA    NUMBER NOT NULL,
    NUMHORAS   NUMBER
);

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_PK PRIMARY KEY ( CODDEPTO,
                                            NUMDISC,
                                            ANOSEM,
                                            SIGLATUR,
                                            DIASEM,
                                            HORAINICIO );

CREATE TABLE PREDIO (
    CODPREDIO       NUMBER NOT NULL,
    DESCRICAOPREDIO VARCHAR2(100)
);

ALTER TABLE PREDIO ADD CONSTRAINT PREDIO_PK PRIMARY KEY ( CODPREDIO );

CREATE TABLE PREREQ (
    CODDEPTO       NUMBER NOT NULL,
    NUMDISC        NUMBER NOT NULL,
    CODDEPTOPREREQ NUMBER NOT NULL,
    NUMDISCPREREQ  NUMBER NOT NULL
);

ALTER TABLE PREREQ
    ADD CONSTRAINT PREREQ_PK PRIMARY KEY ( CODDEPTO,
                                           NUMDISC,
                                           CODDEPTOPREREQ,
                                           NUMDISCPREREQ );

CREATE TABLE PROFESSOR (
    CODPROF  NUMBER NOT NULL,
    CODDEPTO NUMBER,
    CODTIT   NUMBER NOT NULL,
    NOMEPROF VARCHAR2(100)
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_PK PRIMARY KEY ( CODPROF );

CREATE TABLE PROFTURMA (
    CODDEPTO NUMBER NOT NULL,
    NUMDISC  NUMBER NOT NULL,
    ANOSEM   VARCHAR2(5) NOT NULL,
    SIGLATUR VARCHAR2(20) NOT NULL,
    CODPROF  NUMBER NOT NULL
);

ALTER TABLE PROFTURMA
    ADD CONSTRAINT PROFTURMA_PK PRIMARY KEY ( CODDEPTO,
                                              NUMDISC,
                                              ANOSEM,
                                              SIGLATUR,
                                              CODPROF );

CREATE TABLE SALA (
    CODPREDIO     NUMBER NOT NULL,
    NUMSALA       NUMBER NOT NULL,
    DESCRICAOSALA VARCHAR2(100),
    CAPACIDADE    NUMBER
);

ALTER TABLE SALA ADD CONSTRAINT SALA_PK PRIMARY KEY ( NUMSALA,
                                                      CODPREDIO );

CREATE TABLE TITULACAO (
    CODTIT  NUMBER NOT NULL,
    NOMETIT VARCHAR2(100)
);

ALTER TABLE TITULACAO ADD CONSTRAINT TITULACAO_PK PRIMARY KEY ( CODTIT );

CREATE TABLE TURMA (
    CODDEPTO   NUMBER NOT NULL,
    NUMDISC    NUMBER NOT NULL,
    ANOSEM     VARCHAR2(5) NOT NULL,
    SIGLATUR   VARCHAR2(20) NOT NULL,
    CAPACIDADE NUMBER
);

ALTER TABLE TURMA
    ADD CONSTRAINT TURMA_PK PRIMARY KEY ( SIGLATUR,
                                          CODDEPTO,
                                          NUMDISC,
                                          ANOSEM );

ALTER TABLE DISCIPLINA
    ADD CONSTRAINT DISCIPLINA_DEPTO_FK FOREIGN KEY ( CODDEPTO )
        REFERENCES DEPTO ( CODDEPTO );

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_SALA_FK FOREIGN KEY ( NUMSALA,
                                                 CODPREDIO )
        REFERENCES SALA ( NUMSALA,
                          CODPREDIO );

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_TURMA_FK FOREIGN KEY ( SIGLATUR,
                                                  CODDEPTO,
                                                  NUMDISC,
                                                  ANOSEM )
        REFERENCES TURMA ( SIGLATUR,
                           CODDEPTO,
                           NUMDISC,
                           ANOSEM );

ALTER TABLE PREREQ
    ADD CONSTRAINT PREREQ_DISCIPLINA_FK FOREIGN KEY ( NUMDISC,
                                                      CODDEPTO )
        REFERENCES DISCIPLINA ( NUMDISC,
                                CODDEPTO );

ALTER TABLE PREREQ
    ADD CONSTRAINT PREREQ_DISCIPLINA_FKV2 FOREIGN KEY ( NUMDISCPREREQ,
                                                        CODDEPTOPREREQ )
        REFERENCES DISCIPLINA ( NUMDISC,
                                CODDEPTO );

ALTER TABLE PROFESSOR
    ADD CONSTRAINT PROFESSOR_TITULACAO_FK FOREIGN KEY ( CODTIT )
        REFERENCES TITULACAO ( CODTIT );

ALTER TABLE PROFTURMA
    ADD CONSTRAINT PROFTURMA_PROFESSOR_FK FOREIGN KEY ( CODPROF )
        REFERENCES PROFESSOR ( CODPROF );

ALTER TABLE PROFTURMA
    ADD CONSTRAINT PROFTURMA_TURMA_FK FOREIGN KEY ( SIGLATUR,
                                                    CODDEPTO,
                                                    NUMDISC,
                                                    ANOSEM )
        REFERENCES TURMA ( SIGLATUR,
                           CODDEPTO,
                           NUMDISC,
                           ANOSEM );

ALTER TABLE SALA
    ADD CONSTRAINT SALA_PREDIO_FK FOREIGN KEY ( CODPREDIO )
        REFERENCES PREDIO ( CODPREDIO );

ALTER TABLE TURMA
    ADD CONSTRAINT TURMA_DISCIPLINA_FK FOREIGN KEY ( NUMDISC,
                                                     CODDEPTO )
        REFERENCES DISCIPLINA ( NUMDISC,
                                CODDEPTO );


INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES ('1','MESTRADO');
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES ('2','DOUTORADO');
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES ('3','BACHARELADO');
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES ('4','POS DOUTORADO');
INSERT INTO TITULACAO (CODTIT, NOMETIT) VALUES ('5','POS GRADUADO');


INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('1','Inform�tica');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('2','Ci�ncias');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('3','Biologia');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('4','Medicina');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('5','Farm�cia');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('6','Contabilidade');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('7','Administra��o');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('8','Finan�as');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('9','Engenharia');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('10','Odontologia');
INSERT INTO DEPTO (CODDEPTO, NOMEDEPTO) VALUES ('11','Nutri��o');

INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('1','Predio 1');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('2','Predio 2');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('3','Predio 3');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('4','Predio 4');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('5','Predio 5');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('6','Predio 6');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('7','Predio 7');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('8','Predio 8');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('9','Predio 9');
INSERT INTO PREDIO (CODPREDIO, DESCRICAOPREDIO) VALUES ('10','Predio 10');

INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('1','1','Sala 1 Predio 1','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('1','2','Sala 2 Predio 1','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('1','3','Sala 3 Predio 1','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('1','4','Sala 4 Predio 1','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('1','5','Sala 5 Predio 1','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('2','1','Sala 1 Predio 2','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('2','2','Sala 2 Predio 2','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('2','3','Sala 3 Predio 2','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('2','4','Sala 4 Predio 2','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('2','5','Sala 5 Predio 2','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('3','1','Sala 1 Predio 3','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('3','2','Sala 2 Predio 3','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('3','3','Sala 3 Predio 3','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('3','4','Sala 4 Predio 3','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('3','5','Sala 5 Predio 3','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('4','1','Sala 1 Predio 4','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('4','2','Sala 2 Predio 4','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('4','3','Sala 3 Predio 4','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('4','4','Sala 4 Predio 4','50');
INSERT INTO SALA (CODPREDIO, NUMSALA, DESCRICAOSALA, CAPACIDADE ) VALUES ('4','5','Sala 5 Predio 4','50');


INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('1','1','1','JOSE');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('2','1','1','MARIA');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('3','2','1','ANTONIO');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('4','2','1','ROBERTO');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('5','3','2','FLAVIO');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('6','3','2','LEONARDO');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('7','4','2','JOSIMAR');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('8','4','2','RENATA');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('9','5','2','MILLENA');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('10','5','2','ANDRE');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('11','5','2','AUGUSTO');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('12','6','2','RENAN');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('13','6','2','ALICE');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('14','7','1','MARCOS');
INSERT INTO PROFESSOR (CODPROF, CODDEPTO, CODTIT, NOMEPROF) VALUES ('15','7','1','FRANCISCO');


INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('1','1','DISCIPLINA 1','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('1','2','DISCIPLINA 2','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('2','3','DISCIPLINA 3','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('2','4','DISCIPLINA 4','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('3','5','DISCIPLINA 5','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('3','6','DISCIPLINA 6','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('4','7','DISCIPLINA 7','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('4','8','DISCIPLINA 8','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('5','9','DISCIPLINA 9','5');
INSERT INTO DISCIPLINA (CODDEPTO, NUMDISC, NOMEDISC, CREDITODISC) VALUES ('5','10','DISCIPLINA 10','5');


INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('1','1','20022','T1','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('1','1','20022','T2','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('1','2','20022','T3','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('2','3','20022','T4','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('2','3','20022','T5','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('2','3','20022','T6','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('3','5','20022','T7','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('3','6','20022','T8','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('3','6','20022','T9','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('4','7','20022','T10','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('4','7','20022','T11','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('4','8','20022','T12','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('5','9','20022','T13','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('5','10','20022','T14','50');
INSERT INTO TURMA (CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, CAPACIDADE) VALUES ('5','10','20022','T15','50');


INSERT INTO HORARIO
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '1' CODPREDIO, '1' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T1'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '1' CODPREDIO, '2' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T2'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '1' CODPREDIO, '3' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T4'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '1' CODPREDIO, '5' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T5'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '2' CODPREDIO, '1' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T6'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '2' CODPREDIO, '2' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T7'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '2' CODPREDIO, '3' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T8'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '2' CODPREDIO, '4' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T9'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '2' CODPREDIO, '5' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T10'
UNION ALL
SELECT CODDEPTO, NUMDISC, ANOSEM, SIGLATUR, 'SEGUNDA' DIASEM, '18:50' HORAINICIO, '3' CODPREDIO, '1' CODSALA, '4' NUMHORAS FROM TURMA WHERE SIGLATUR = 'T11'

INSERT INTO PROFTURMA
SELECT T.CODDEPTO, T.NUMDISC, T.ANOSEM, T.SIGLATUR, P.CODPROF
FROM TURMA T,
     PROFESSOR P
WHERE ROWNUM <= 50

COMMIT;


/* -------------------------------------------RESPOSTAS ---------------------------------------*/
-- 1 - OBTER OS ANO-SEMESTRE EM QUE TODOS OS PROFESSORES DO DEPARTAMENTO INFORMATICA DERAM AULA
SELECT ANOSEM FROM PROFTURMA WHERE CODDEPTO IN (SELECT CODDEPTO FROM DEPTO WHERE NOMEDEPTO = 'Informática')

-- 2 - OBTER O NUMERO DE SALAS QUE FORAM USADAS NO ANO-SEMESTRE 20022 POR TURMAS DO DEPARTAMENTO DENOMINADO INFORMATICA
WITH SALAS_PREDIO AS (
SELECT COUNT(DISTINCT NUMSALA) QT_SALAS, CODPREDIO
FROM HORARIO
WHERE ANOSEM = '20022'
AND CODDEPETO IN (SELECT CODDEPTO FROM DEPTO WHERE NOMEDEPTO = 'Informática')
)
SELECT SUM(QT_SALAS) TOTAL
FROM SALAS_PREDIO


--QUESTAO 2
CREATE TABLE TABELA_PRAZO
(
 CEP_INICIO NUMBER(8) NOT NULL
, CEP_FIM NUMBER(8) NOT NULL
, PRAZO NUMBER(3) NOT NULL
);

INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('1000000','1000005','5');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('510101','510104','4');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('510000','510067','4');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('510068','510100','3');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('1000006','10000010','5');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('810000','810001','5');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('810002','810003','5');
INSERT INTO TABELA_PRAZO (CEP_INICIO, CEP_FIM, PRAZO) VALUES ('810004','810005','5');


CREATE TABLE TABELA_PRAZO_COMPACTADO
(
 CEP_INICIO NUMBER(8) NOT NULL
, CEP_FIM NUMBER(8) NOT NULL
, PRAZO NUMBER(3) NOT NULL
);

-- RESPOSTA
INSERT INTO TABELA_PRAZO_COMPACTADO
WITH PRAZO_FAIXA AS (
SELECT CEP_INICIO, 
       CEP_FIM, 
       PRAZO, 
       SUBSTR(CEP_INICIO, 0, LENGTH(CEP_INICIO)-2) FAIXA_INI,
       DECODE(SUBSTR(CEP_FIM, LENGTH(CEP_FIM)-1, LENGTH(CEP_FIM)),10, SUBSTR(CEP_FIM, 0, LENGTH(CEP_FIM)-3), SUBSTR(CEP_FIM, 0, LENGTH(CEP_FIM)-2)) FAIXA_FIM 
FROM TABELA_PRAZO
),
PRAZOS AS (
SELECT MIN(CEP_INICIO) CEP_INICIO, MAX(CEP_FIM) CEP_FIM, PRAZO, FAIXA_INI, FAIXA_FIM
FROM PRAZO_FAIXA
GROUP BY PRAZO, FAIXA_INI, FAIXA_FIM
)
SELECT CEP_INICIO, CEP_FIM, PRAZO
FROM PRAZOS;

COMMIT;


--QUESTAO 3
CREATE *TABLE EVENTS (
EVENT_TYPE INTEGER NOT NULL,
VALUE INTEGER NOT NULL,
TIME TIMESTAMP NOT NULL,
UNIQUE (EVENT_TYPE, TIME)
);


INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (2, 5, TO_TIMESTAMP('2015-05-09 12:42:00','YYYY-MM-DD-HH24:MI:SS'));
INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (4, -42, TO_TIMESTAMP('2015-05-09 13:19:57','YYYY-MM-DD-HH24:MI:SS'));
INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (2, 2, TO_TIMESTAMP('2015-05-09 14:48:30','YYYY-MM-DD-HH24:MI:SS'));
INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (2, 7, TO_TIMESTAMP('2015-05-09 12:54:39','YYYY-MM-DD-HH24:MI:SS'));
INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (3, 16, TO_TIMESTAMP('2015-05-09 13:19:57','YYYY-MM-DD-HH24:MI:SS'));
INSERT INTO EVENTS (EVENT_TYPE, VALUE, TIME) VALUES (3, 20, TO_TIMESTAMP('2015-05-09 15:01:09','YYYY-MM-DD-HH24:MI:SS'));


WITH REPEATED_EVENTS AS (
SELECT COUNT(EVENT_TYPE) QT, EVENT_TYPE
FROM EVENTS
HAVING COUNT(EVENT_TYPE) > 1
GROUP BY EVENT_TYPE
ORDER BY EVENT_TYPE
), 
EVENT_DATA AS (
SELECT E.EVENT_TYPE, 
       E.VALUE, 
       E.TIME, 
       LEAD(E.VALUE, 2) OVER( PARTITION BY E.EVENT_TYPE ORDER BY E.EVENT_TYPE) PENULTIMO,
       (SELECT VALUE FROM EVENTS WHERE EVENT_TYPE = E.EVENT_TYPE AND TIME = (SELECT MIN(TIME) FROM EVENTS WHERE EVENT_TYPE =  E.EVENT_TYPE)) OLDEST
FROM EVENTS E
INNER JOIN REPEATED_EVENTS RE ON RE.EVENT_TYPE = E.EVENT_TYPE
)
SELECT EVENT_TYPE, SUM(NVL(PENULTIMO - OLDEST,0)) VALUE
FROM EVENT_DATA
GROUP BY EVENT_TYPE
ORDER BY EVENT_TYPE